version: '2'
services:
  excursions-api6:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      LOGIN_ENTRY: "/sign_in"
      SIGN_UP_ENTRY: "/sign_up"
      AUTHORIZATION_ENTRY: "/authorize"
    labels:
      io.rancher.scheduler.global: 'true'
    ports:
      - '5001:5000'
    external_links:
      # <stackname>/<service_name>:<service_alias>
      - bookings-ms/web
      - notifications-ms/notifications-lb
      - packages-ms/myapp2
      - suppliers-ms/web
      - payments-ms/paymentsms
      - authorization-ms/web6