version: '2'
services:
  excursions-app-api6:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      LOGIN_URL: ""
      LOGIN_PORT: ""
      LOGIN_ENTRY: ""
    ports:
      - '5000:5000'
