version: '2'
services:
  excursions-api3:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      LOGIN_URL: ""
      LOGIN_PORT: ""
      LOGIN_ENTRY: ""
    labels:
      io.rancher.scheduler.affinity:host_label: io.rancher.stack.name=api
      io.rancher.scheduler.global: 'true'
    ports:
      - '5000:5000'
